--- 
- hosts: 172.31.47.241
  become: yes
  tasks:
  - name: i want to run shell command
    command: hostname -f 
    register: myhostname

  - name: i want to display the result 
    debug: 
      msg: "{{myhostname}}"
     