---
- hosts: 172.31.47.241
  become: yes
  tasks: 
  - name: i want to install a webserver
    apt: 
      name: apache2
      state: present

  - name: i want to copy a file
    copy: 
      src: mytestfile.txt
      dest: /home/ubuntu/mytxtfile.txt

  - name: i want to handle dynamic file inbox.j2
    template: 
      src: myindex.j2
      dest: /var/www/html/index.html
