---
- hosts: 172.31.47.241
  become: yes
  tasks: 
  - name: i want to install a webserver
    apt: 
      name: apache2
      state: present

  - name: i want to copy a file
    copy: 
      src: mytestfile.txt
      dest: /home/ubuntu/mytxtfile.txt
    notify: Restart webserver

  - name: i want to handle dynamic file inbox.j2
    template: 
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: Restart webserver

  - name: Downloading file from internet 
    get_url:
      url:  https://get.jenkins.io/war-stable/2.426.3/jenkins.war
      dest: /home/ubuntu
      force_basic_auth: yes 

  handlers:
  - name: Restart webserver
    service: 
      name: apache2
      state: restarted

