---
- hosts: mywebservers
  become: yes
  tasks:
    - name: I want to install webserver on Ubutntu nodes
      apt:
        name: "{{webpackonubuntu}}"
        state: present
      when: ansible_os_family == "Debian"

    - name: I want to start apache2 
      service:
        name: "{{webpackonubuntu}}"
        state: started
      when: ansible_os_family == "Debian"

    - name: I want to install webserver on Redhat 
      yum:
        name: "{{webpackonredhat}}"
        state: present 
      when: ansible_os_family == "RedHat"

    - name: Start httpd 
      service:
        name: "{{webpackonredhat}}"
        state: started
      when: ansible_os_family == "RedHat"
