---
- hosts: all
  become: yes
  tasks:
    - name: I want to install webserver on Ubutntu nodes
      apt:
        name: apache2
        state: present

    - name: I want to start apache2 
      service:
        name: apache2
        state: restarted

    - name: Uninstall apache2
      apt:
        name: apache2
        state: absent